export const dummy = {
  "dates": {
    "maximum": "2025-01-15",
    "minimum": "2024-12-04"
  },
  "page": 1,
  "results": [
    {
      "adult": false,
      "backdrop_path": "/zOpe0eHsq0A2NvNyBbtT6sj53qV.jpg",
      "genre_ids": [28, 878, 35, 10751],
      "id": 939243,
      "original_language": "en",
      "original_title": "Sonic the Hedgehog 3",
      "overview": "Sonic, Knuckles, and Tails reunite against a powerful new adversary, Shadow, a mysterious villain with powers unlike anything they have faced before. With their abilities outmatched in every way, Team Sonic must seek out an unlikely alliance in hopes of stopping Shadow and protecting the planet.",
      "popularity": 3088.942,
      "poster_path": "/d8Ryb8AunYAuycVKDp5HpdWPKgC.jpg",
      "release_date": "2024-12-19",
      "title": "Sonic the Hedgehog 3",
      "video": false,
      "vote_average": 7.626,
      "vote_count": 529
    },
    {
      "adult": false,
      "backdrop_path": "/euYIwmwkmz95mnXvufEmbL6ovhZ.jpg",
      "genre_ids": [28, 12, 18],
      "id": 558449,
      "original_language": "en",
      "original_title": "Gladiator II",
      "overview": "Years after witnessing the death of the revered hero Maximus at the hands of his uncle, Lucius is forced to enter the Colosseum after his home is conquered by the tyrannical Emperors who now lead Rome with an iron fist. With rage in his heart and the future of the Empire at stake, Lucius must look to his past to find strength and honor to return the glory of Rome to its people.",
      "popularity": 2793.693,
      "poster_path": "/2cxhvwyEwRlysAmRH4iodkvo0z5.jpg",
      "release_date": "2024-11-05",
      "title": "Gladiator II",
      "video": false,
      "vote_average": 6.766,
      "vote_count": 2283
    },
    {
      "adult": false,
      "backdrop_path": "/oHPoF0Gzu8xwK4CtdXDaWdcuZxZ.jpg",
      "genre_ids": [12, 10751, 16],
      "id": 762509,
      "original_language": "en",
      "original_title": "Mufasa: The Lion King",
      "overview": "Mufasa, a cub lost and alone, meets a sympathetic lion named Taka, the heir to a royal bloodline. The chance meeting sets in motion an expansive journey of a group of misfits searching for their destiny.",
      "popularity": 2932.613,
      "poster_path": "/jbOSUAWMGzGL1L4EaUF8K6zYFo7.jpg",
      "release_date": "2024-12-18",
      "title": "Mufasa: The Lion King",
      "video": false,
      "vote_average": 7.4,
      "vote_count": 626
    },
    {
      "adult": false,
      "backdrop_path": "/vYqt6kb4lcF8wwqsMMaULkP9OEn.jpg",
      "genre_ids": [16, 12, 10751, 35],
      "id": 1241982,
      "original_language": "en",
      "original_title": "Moana 2",
      "overview": "After receiving an unexpected call from her wayfinding ancestors, Moana journeys alongside Maui and a new crew to the far seas of Oceania and into dangerous, long-lost waters for an adventure unlike anything she's ever faced.",
      "popularity": 1994.752,
      "poster_path": "/aLVkiINlIeCkcZIzb7XHzPYgO6L.jpg",
      "release_date": "2024-11-21",
      "title": "Moana 2",
      "video": false,
      "vote_average": 7.011,
      "vote_count": 839
    },
    {
      "adult": false,
      "backdrop_path": "/uKb22E0nlzr914bA9KyA5CVCOlV.jpg",
      "genre_ids": [18, 10749, 14],
      "id": 402431,
      "original_language": "en",
      "original_title": "Wicked",
      "overview": "In the land of Oz, ostracized and misunderstood green-skinned Elphaba is forced to share a room with the popular aristocrat Glinda at Shiz University, and the two's unlikely friendship is tested as they begin to fulfill their respective destinies as Glinda the Good and the Wicked Witch of the West.",
      "popularity": 1592.229,
      "poster_path": "/xDGbZ0JJ3mYaGKy4Nzd9Kph6M9L.jpg",
      "release_date": "2024-11-20",
      "title": "Wicked",
      "video": false,
      "vote_average": 7.2,
      "vote_count": 1237
    },
    {
      "adult": false,
      "backdrop_path": "/ie8OSgIHEl6yQiGJ90dsyBWOpQA.jpg",
      "genre_ids": [16, 14, 28, 12],
      "id": 839033,
      "original_language": "en",
      "original_title": "The Lord of the Rings: The War of the Rohirrim",
      "overview": "A sudden attack by Wulf, a clever and traitorous lord of Rohan seeking vengeance for the death of his father, forces Helm Hammerhand, the King of Rohan, and his people to make a daring last stand in the ancient stronghold of the Hornburg.",
      "popularity": 1421.283,
      "poster_path": "/cXzCOx1hUuU9CfmiEv6rXjb6EqU.jpg",
      "release_date": "2024-12-05",
      "title": "The Lord of the Rings: The War of the Rohirrim",
      "video": false,
      "vote_average": 6.5,
      "vote_count": 300
    },
    {
      "adult": false,
      "backdrop_path": "/fzjH7kt1017R9EckLDmWmH5pGhD.jpg",
      "genre_ids": [28, 27, 53],
      "id": 970450,
      "original_language": "en",
      "original_title": "Werewolves",
      "overview": "A year after a supermoon’s light activated a dormant gene, transforming humans into bloodthirsty werewolves and causing nearly a billion deaths, the nightmare resurfaces as the supermoon rises again. Two scientists attempt to stop the mutation but fail and must now struggle to reach one of their family homes.",
      "popularity": 1277.066,
      "poster_path": "/cRTctVlwvMdXVsaYbX5qfkittDP.jpg",
      "release_date": "2024-12-04",
      "title": "Werewolves",
      "video": false,
      "vote_average": 6.356,
      "vote_count": 170
    },
    {
      "adult": false,
      "backdrop_path": "/k24eZq5I3jyz4htPkZCRpnUmBzE.jpg",
      "genre_ids": [10749, 18],
      "id": 1156593,
      "original_language": "es",
      "original_title": "Culpa tuya",
      "overview": "The love between Noah and Nick seems unwavering despite their parents' attempts to separate them. But his job and her entry into college open up their lives to new relationships that will shake the foundations of both their relationship and the Leister family itself.",
      "popularity": 1259.594,
      "poster_path": "/1sQA7lfcF9yUyoLYC0e6Zo3jmxE.jpg",
      "release_date": "2024-12-26",
      "title": "Your Fault",
      "video": false,
      "vote_average": 7.142,
      "vote_count": 838
    },
    {
      "adult": false,
      "backdrop_path": "/cjEcqdRdPQJhYre3HUAc5538Gk8.jpg",
      "genre_ids": [28, 14, 35],
      "id": 845781,
      "original_language": "en",
      "original_title": "Red One",
      "overview": "After Santa Claus (codename: Red One) is kidnapped, the North Pole's Head of Security must team up with the world's most infamous tracker in a globe-trotting, action-packed mission to save Christmas.",
      "popularity": 1533.747,
      "poster_path": "/cdqLnri3NEGcmfnqwk2TSIYtddg.jpg",
      "release_date": "2024-10-31",
      "title": "Red One",
      "video": false,
      "vote_average": 7.1,
      "vote_count": 1995
    },
    {
      "adult": false,
      "backdrop_path": "/au3o84ub27qTZiMiEc9UYzN74V3.jpg",
      "genre_ids": [28, 878, 53],
      "id": 1035048,
      "original_language": "en",
      "original_title": "Elevation",
      "overview": "A single father and two women venture from the safety of their homes to face monstrous creatures to save the life of a young boy.",
      "popularity": 1242.49,
      "poster_path": "/tnfc0NJ3BzhJrGJhkkEd6MHBdq5.jpg",
      "release_date": "2024-11-07",
      "title": "Elevation",
      "video": false,
      "vote_average": 6.269,
      "vote_count": 323
    },
    {
      "adult": false,
      "backdrop_path": "/b3mdmjYTEL70j7nuXATUAD9qgu4.jpg",
      "genre_ids": [16, 14, 12],
      "id": 823219,
      "original_language": "lv",
      "original_title": "Straume",
      "overview": "A solitary cat, displaced by a great flood, finds refuge on a boat with various species and must navigate the challenges of adapting to a transformed world together.",
      "popularity": 966.429,
      "poster_path": "/imKSymKBK7o73sajciEmndJoVkR.jpg",
      "release_date": "2024-01-30",
      "title": "Flow",
      "video": false,
      "vote_average": 8.4,
      "vote_count": 727
    },
    {
      "adult": false,
      "backdrop_path": "/rhc8Mtuo3Kh8CndnlmTNMF8o9pU.jpg",
      "genre_ids": [53, 28],
      "id": 1005331,
      "original_language": "en",
      "original_title": "Carry-On",
      "overview": "An airport security officer races to outsmart a mysterious traveler forcing him to let a dangerous item slip onto a Christmas Eve flight.",
      "popularity": 927.035,
      "poster_path": "/sjMN7DRi4sGiledsmllEw5HJjPy.jpg",
      "release_date": "2024-12-05",
      "title": "Carry-On",
      "video": false,
      "vote_average": 6.934,
      "vote_count": 1609
    },
    {
      "adult": false,
      "backdrop_path": "/dWkdmxIkH9y23s9v1PjQFhTGIwo.jpg",
      "genre_ids": [28, 18, 53],
      "id": 1043905,
      "original_language": "en",
      "original_title": "Dirty Angels",
      "overview": "During the United States' 2021 withdrawal from Afghanistan, a group of female soldiers posing as medical relief are sent back in to rescue a group of kidnapped teenagers caught between ISIS and the Taliban.",
      "popularity": 1074.447,
      "poster_path": "/3O3qSGmjRGc10hMwFul8WDxKE5t.jpg",
      "release_date": "2024-12-11",
      "title": "Dirty Angels",
      "video": false,
      "vote_average": 6.5,
      "vote_count": 118
    },
    {
      "adult": false,
      "backdrop_path": "/6lE2e6j8qbtQR8aHxQNJlwxdmKV.jpg",
      "genre_ids": [28, 80, 53],
      "id": 974453,
      "original_language": "en",
      "original_title": "Absolution",
      "overview": "An aging ex-boxer gangster working as muscle for a Boston crime boss receives an upsetting diagnosis.  Despite a faltering memory, he attempts to rectify the sins of his past and reconnect with his estranged children. He is determined to leave a positive legacy for his grandson, but the criminal underworld isn’t done with him and won’t loosen their grip willingly.",
      "popularity": 745.47,
      "poster_path": "/2MeQG5Vq8rUnRAa463BZe5GNhVk.jpg",
      "release_date": "2024-10-31",
      "title": "Absolution",
      "video": false,
      "vote_average": 5.855,
      "vote_count": 251
    },
    {
      "adult": false,
      "backdrop_path": "/7h6TqPB3ESmjuVbxCxAeB1c9OB1.jpg",
      "genre_ids": [27, 878],
      "id": 933260,
      "original_language": "en",
      "original_title": "The Substance",
      "overview": "A fading celebrity decides to use a black market drug, a cell-replicating substance that temporarily creates a younger, better version of herself.",
      "popularity": 866.5,
      "poster_path": "/lqoMzCcZYEFK729d6qzt349fB4o.jpg",
      "release_date": "2024-09-07",
      "title": "The Substance",
      "video": false,
      "vote_average": 7.127,
      "vote_count": 3228
    },
    {
      "adult": false,
      "backdrop_path": "/uWOJbarUXfVf6B4o0368dh138eR.jpg",
      "genre_ids": [18, 14, 27],
      "id": 426063,
      "original_language": "en",
      "original_title": "Nosferatu",
      "overview": "A gothic tale of obsession between a haunted young woman and the terrifying vampire infatuated with her, causing untold horror in its wake.",
      "popularity": 734.436,
      "poster_path": "/5qGIxdEO841C0tdY8vOdLoRVrr0.jpg",
      "release_date": "2024-12-25",
      "title": "Nosferatu",
      "video": false,
      "vote_average": 6.8,
      "vote_count": 921
    },
    {
      "adult": false,
      "backdrop_path": "/A28EE0vgHrB0OdoxWWMfgfyEoYn.jpg",
      "genre_ids": [80, 53, 28],
      "id": 1276945,
      "original_language": "nl",
      "original_title": "Ferry 2",
      "overview": "After losing his drug empire, Ferry Bouman has found a measure of peace away from Brabant's criminal underworld — until his past catches up to him.",
      "popularity": 665.212,
      "poster_path": "/8pwdnL3pEISIN1EGmwZzU6hpNVk.jpg",
      "release_date": "2024-12-19",
      "title": "Ferry 2",
      "video": false,
      "vote_average": 5.628,
      "vote_count": 86
    },
    {
      "adult": false,
      "backdrop_path": "/ag66gJCiZ06q1GSJuQlhGLi3Udx.jpg",
      "genre_ids": [27, 53],
      "id": 1138194,
      "original_language": "en",
      "original_title": "Heretic",
      "overview": "Two young missionaries are forced to prove their faith when they knock on the wrong door and are greeted by a diabolical Mr. Reed, becoming ensnared in his deadly game of cat-and-mouse.",
      "popularity": 620.689,
      "poster_path": "/5HJqjCTcaE1TFwnNh3Dn21be2es.jpg",
      "release_date": "2024-10-31",
      "title": "Heretic",
      "video": false,
      "vote_average": 7.197,
      "vote_count": 831
    },
    {
      "adult": false,
      "backdrop_path": "/ovt5KdS1oNwXkFPsgymhMoKvxKa.jpg",
      "genre_ids": [16, 35, 10751, 12],
      "id": 929204,
      "original_language": "en",
      "original_title": "Wallace & Gromit: Vengeance Most Fowl",
      "overview": "Gromit’s concern that Wallace is becoming too dependent on his inventions proves justified, when Wallace invents a “smart” gnome that seems to develop a mind of its own. When it emerges that a vengeful figure from the past might be masterminding things, it falls to Gromit to battle sinister forces and save his master… or Wallace may never be able to invent again!",
      "popularity": 534.193,
      "poster_path": "/6BxK38ehxuX2dJmZIMpJcVNbYks.jpg",
      "release_date": "2024-12-18",
      "title": "Wallace & Gromit: Vengeance Most Fowl",
      "video": false,
      "vote_average": 7.759,
      "vote_count": 226
    },
    {
      "adult": false,
      "backdrop_path": "/v9Du2HC3hlknAvGlWhquRbeifwW.jpg",
      "genre_ids": [28, 12, 53],
      "id": 539972,
      "original_language": "en",
      "original_title": "Kraven the Hunter",
      "overview": "Kraven Kravinoff's complex relationship with his ruthless gangster father, Nikolai, starts him down a path of vengeance with brutal consequences, motivating him to become not only the greatest hunter in the world, but also one of its most feared.",
      "popularity": 613.071,
      "poster_path": "/i47IUSsN126K11JUzqQIOi1Mg1M.jpg",
      "release_date": "2024-12-11",
      "title": "Kraven the Hunter",
      "video": false,
      "vote_average": 5.9,
      "vote_count": 306
    }
  ],
  "total_pages": 207,
  "total_results": 4132
}